### ISSUE TITLE
Error with npm run setup in NodeJS 22 LTS:

### ISSUE THREAD

**Issue by boddedo** [KSJaay/Lunalytics#57]
Hello !

When I execute `npm run setup` with NodeJS 22.12.0

I have this error:
```
> lunalytics@0.6.4 setup
> npm install && node ./scripts/basic_setup.js && npm run build

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path /home/user/repo/Lunalytics/node_modules/better-sqlite3
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild --release
npm error prebuild-install warn install No prebuilt binaries found (target=22.12.0 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@22.12.0 | linux | x64
npm error gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/user/repo/Lunalytics/node_modules/better-sqlite3/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/user/.cache/node-gyp/22.12.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/user/.cache/node-gyp/22.12.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/user/.cache/node-gyp/22.12.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/user/repo/Lunalytics/node_modules/better-sqlite3',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:119:22)
npm error gyp ERR! stack at async loadConfigGypi (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:78:7)
npm error gyp ERR! stack at async build (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:36:3)
npm error gyp ERR! stack at async run (/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 6.8.0-47-generic
npm error gyp ERR! command "/home/user/node/v22.12.0/bin/node" "/home/user/node/v22.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm error gyp ERR! cwd /home/user/repo/Lunalytics/node_modules/better-sqlite3
npm error gyp ERR! node -v v22.12.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/user/.npm/_logs/2024-12-05T15_50_59_820Z-debug-0.log
```

it seem a dependency problem.
Have a good day !

**Comment by KSJaay** [comment]
Hey, the current recommended version is `20.11.1`. I haven't upgraded to newer version of Nodejs yet.

**Comment by KSJaay** [comment]
With React 19 being released earlier today, I will be updating to React 19 along with a newer version of Nodejs.

**Comment by boddedo** [comment]
Okay thank you !

I have also some other question and also weird bug should I put everything in this issue, or you prefer have 1 issue by feature/bug ?

**Comment by KSJaay** [comment]
If the feature/bug has nothing to do with this one, then I'd prefer if you start a new issue please :)

**Comment by KSJaay** [comment]
This will be fixed as apart of https://github.com/KSJaay/Lunalytics/pull/67/files
